name: benchmark_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - sparqlwrapper
  - rdflib
  - pathlib
  - pandas
  - requests
  - zipfile2
  - matplotlib
  - jinja2
  - plotly