name: Run Workflow and Deploy to GitHub Pages

permissions:
  contents: write


on:
  push:
    branches:
      - main  # Run the workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Optionally run on pull requests to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9  # Use the Python version compatible with your script

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r python-utils/requirements.txt  # Ensure you have a requirements.txt file

    # Step 4: Run the workflow.py script
    - name: Run workflow.py
      run: |
        cd python-utils
        python workflow.py

    # Debugging step: Check if the dashboard directory exists
    - name: Check dashboard directory
      run: ls -la ./dashboard

    # Step 5: Deploy the dashboard folder to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dashboard  # Path to the folder containing the HTML files